# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
githubRepository: apache/airflow

scaleDownDelaySecondsAfterScaleOut: 30

common:
  runnersLabels:
    - airflow-runner
    - eks-runner

runners:
  - name: small
    minReplicas: 0
    maxReplicas: 30
    labels:
      - small
      - arm64
    nodeSelector:
      node-type: gha-runners
      size: small
      arch: arm64
    tolerations:
      - key: node-type
        operator: Equal
        value: gha-runners
        effect: NoSchedule
  - name: medium
    minReplicas: 0
    maxReplicas: 30
    labels:
      - medium
      - arm64
    nodeSelector:
      node-type: gha-runners
      size: medium
      arch: arm64
    tolerations:
      - key: node-type
        operator: Equal
        value: gha-runners
        effect: NoSchedule
  - name: large
    minReplicas: 0
    maxReplicas: 30
    labels:
      - large
      - arm64
    nodeSelector:
      node-type: gha-runners
      size: large
      arch: arm64
    tolerations:
      - key: node-type
        operator: Equal
        value: gha-runners
        effect: NoSchedule
  - name: small-x86
    minReplicas: 0
    maxReplicas: 30
    labels:
      - small
      - x86
    nodeSelector:
      node-type: gha-runners
      size: small
      arch: x86
    tolerations:
      - key: node-type
        operator: Equal
        value: gha-runners
        effect: NoSchedule
  - name: medium-x86
    minReplicas: 0
    maxReplicas: 30
    labels:
      - medium
      - x86
    nodeSelector:
      node-type: gha-runners
      size: medium
      arch: x86
    tolerations:
      - key: node-type
        operator: Equal
        value: gha-runners
        effect: NoSchedule
  - name: large-x86
    minReplicas: 0
    maxReplicas: 30
    labels:
      - large
      - x86
    nodeSelector:
      node-type: gha-runners
      size: large
      arch: x86
    tolerations:
      - key: node-type
        operator: Equal
        value: gha-runners
        effect: NoSchedule
