githubRepository: hussein-awala/airflow

scaleDownDelaySecondsAfterScaleOut: 30

runners:
  - name: small
    minReplicas: 0
    maxReplicas: 5
    labels:
      - small
    nodeSelector:
      node-type: gha-runners
      size: small
    tolerations:
      - key: node-type
        operator: Equal
        value: gha-runners
        effect: NoSchedule
  - name: medium
    minReplicas: 0
    maxReplicas: 5
    labels:
      - medium
    nodeSelector:
      node-type: gha-runners
      size: medium
    tolerations:
      - key: node-type
        operator: Equal
        value: gha-runners
        effect: NoSchedule