#cloud-config
# 2021-05-17 09:21+01:00

mounts:
  - [tmpfs, /tmp, tmpfs, "defaults,noatime,size=10%"]
  - [tmpfs, /var/lib/docker, tmpfs, "defaults,noatime,size=66%"]
  - [tmpfs, /home/runner/actions-runner/_work, tmpfs, "defaults,noatime"]


runcmd:
  -
    - bash
    - -c
    - |
      set -eu -o pipefail
      echo "AWS_DEFAULT_REGION=$(cloud-init query region)" >> /etc/environment
      echo "AWS_DEFAULT_REGION=$(cloud-init query region)" >> /etc/default/vector
      systemctl enable --now vector
      systemctl enable --now actions.runner
