#cloud-config
# 2022-01-21 19:31 BMT

mounts:
  - [tmpfs, /var/lib/docker, tmpfs, "defaults,noatime,size=85%"]
  - [tmpfs, /home/runner/actions-runner/_work, tmpfs, "defaults,noatime"]


runcmd:
  -
    - bash
    - -c
    - |
      set -eu -o pipefail
      echo "AWS_DEFAULT_REGION=$(cloud-init query region)" >> /etc/environment
      echo "AWS_DEFAULT_REGION=$(cloud-init query region)" >> /etc/default/vector
      #aws logs create-log-stream --log-group-name GitHubRunners --log-stream-name $(hostname) || true
      #systemctl enable --now vector
      systemctl enable --now actions.runner
      sysctl -w net.netfilter.nf_conntrack_tcp_be_liberal=1
