#!/usr/bin/env python

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

import boto3
import json
import toml


with open("authors.toml") as handle:
    author_list = toml.load(handle)

author_set = set()
for membership in author_list:
    author_set.update([author for author in author_list[membership]])


ssm_client = boto3.client("ssm")
param = ssm_client.get_parameter(
    Name="/runners/apache/airflow/configOverlay",
)

config = json.loads(param)
config["pullRequestSecurity"]["allowedAuthors"] = author_set

ssm_client.put_parameter(
    Name="/runners/apache/airflow/configOverlay",
    Value=json.dumps(config),
    Type="String",
    Overwrite=True,
)
