apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: small-runners-deployment
spec:
  template:
    spec:
      repository: hussein-awala/airflow
      nodeSelector:
        node-type: gha-runners
        size: small
      tolerations:
        - key: node-type
          operator: Equal
          value: gha-runners
          effect: NoSchedule
      labels:
        - size:small
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: small-runners-deployment-autoscaler
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: small-runners-deployment
  minReplicas: 0
  maxReplicas: 5
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'
      scaleDownThreshold: '0.25'
      scaleUpFactor: '2'
      scaleDownFactor: '0.5'