---
repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: actions-runner-controller
    url: https://actions-runner-controller.github.io/actions-runner-controller

releases:
  - name: cluster-config
    chart: ./cluster-config
    namespace: kube-system

  # https://cert-manager.io/docs/installation/helm/
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: infra
    version: v1.12.2
    values:
      - ./values/cert-manager.yaml

  - name: actions-runner-controller
    chart: actions-runner-controller/actions-runner-controller
    namespace: ci
    version: 0.23.3
    values:
      - ./values/actions-runner-controller.yaml